name: sereni_app
description: "AI-driven mental health companion"
publish_to: 'none'


environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.0
    

  # State Management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

  # Firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.2

  # UI Components
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0

  # Utilities
  intl: ^0.19.0
  logger: ^2.5.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  flutter_quill: ^11.0.0
  flutter_dotenv: ^5.2.1
  connectivity_plus: ^6.1.3

  # AI/ML
  google_generative_ai: ^0.4.6
  
  # Multilingual support 
  # easy_localization: ^3.0.0

  # PDF & Reports
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # Analytics
  firebase_analytics: ^11.4.2
  
  # cupertino icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  bloc_test: ^10.0.0
  mockito: ^5.4.4


flutter:
  assets:
    - assets/logos/sereni_logo.png
    - assets/gifs/welcome_sereni_bot.gif
    - assets/gifs/onboarding_name_bot.gif
    - assets/gifs/onboarding_gender_bot.gif
    - assets/gifs/onboarding_age_bot.gif
    - assets/gifs/sign_in.gif
    - assets/gifs/sign_up.gif
    - assets/images/placeholder_profile.png
    - lib/core/utils/translations/
    - .env


  uses-material-design: true
